Repository shepmaster/snafu, pull requests merged in 2019-11, with the labels that each got.

#189 Reorganize backtraces in preparation for supporting standard library
  .cirrus.yml
  Cargo.toml
  compatibility-tests/backtraces-impl-backtrace-crate/Cargo.toml
  compatibility-tests/backtraces-impl-backtrace-crate/src/lib.rs
  snafu-derive/src/lib.rs
  src/backtrace_inert.rs
  src/backtrace_shim.rs
  src/guide/feature_flags.md
  src/lib.rs
  tests/backtrace-optional-enabled.rs
  tests/backtrace-optional.rs
Labels: breaking change, maintenance

#173 Add support for standard library std::backtrace::Backtrace
  .cirrus.yml
  Cargo.toml
  compatibility-tests/backtraces-impl-std/Cargo.toml
  compatibility-tests/backtraces-impl-std/rust-toolchain
  compatibility-tests/backtraces-impl-std/src/lib.rs
  snafu-derive/Cargo.toml
  snafu-derive/src/lib.rs
  src/lib.rs
Labels: enhancement

#190 Stabilize standard-library futures support
  .cirrus.yml
  Cargo.toml
  compatibility-tests/futures/Cargo.toml
  compatibility-tests/futures/rust-toolchain
  src/futures/mod.rs
  src/futures/try_future.rs
  src/futures/try_stream.rs
  src/futures01/future.rs
  src/futures01/mod.rs
  src/futures01/stream.rs
  src/guide/feature_flags.md
  src/lib.rs
  src/no_std_error.rs
Labels: breaking change, maintenance

#191 Documentation and CI busywork in preparation for 0.6
  .cirrus.yml
  CHANGELOG.md
  Cargo.toml
  src/guide/attributes.md
  src/guide/feature_flags.md
  src/guide/upgrading.md
  src/lib.rs
Labels: maintenance

#194 Update error message from new stable Rust
  compatibility-tests/compile-fail/tests/ui/error-reporting.stderr
Labels: maintenance

#193 Add support for contextless errors
  compatibility-tests/compile-fail/tests/ui/attribute-misuse.rs
  compatibility-tests/compile-fail/tests/ui/attribute-misuse.stderr
  compatibility-tests/compile-fail/tests/ui/no_context.rs
  compatibility-tests/compile-fail/tests/ui/no_context.stderr
  snafu-derive/src/lib.rs
  src/guide/attributes.md
  tests/no_context.rs
Labels: enhancement

#196 Remove unneeded `ref` keywords
  snafu-derive/src/lib.rs
Labels: maintenance

#195 DRY up the error messages
  compatibility-tests/compile-fail/tests/ui/attribute-misuse.stderr
  compatibility-tests/compile-fail/tests/ui/duplication-backtrace-delegate.stderr
  compatibility-tests/compile-fail/tests/ui/duplication-backtrace-fields.stderr
  compatibility-tests/compile-fail/tests/ui/duplication-enum.stderr
  compatibility-tests/compile-fail/tests/ui/duplication-multiple-attributes.stderr
  compatibility-tests/compile-fail/tests/ui/duplication-source-attributes.stderr
  compatibility-tests/compile-fail/tests/ui/duplication-source-from.stderr
  compatibility-tests/compile-fail/tests/ui/duplication-struct.stderr
  compatibility-tests/compile-fail/tests/ui/duplication-variant.stderr
  snafu-derive/src/lib.rs
Labels: maintenance
