Repository shepmaster/snafu, pull requests merged in 2019-07, with the labels that each got.

#108 Update expected stderr outputs for new compiler version
  compatibility-tests/compile-fail/tests/ui/error-reporting.stderr
  compatibility-tests/compile-fail/tests/ui/visibility.stderr
Labels: maintenance

#107 Implement Doc Comments as Default Display Implementations
  snafu-derive/src/lib.rs
  tests/doc_comment.rs
Labels: enhancement

#120 Update changelog and guide for 0.4.2
  CHANGELOG.md
  src/guide/attributes.md
Labels: maintenance

#122 Disallow warnings in CI
  .cirrus.yml
  compatibility-tests/futures-0.1/src/lib.rs
  compatibility-tests/futures/src/lib.rs
  compatibility-tests/v1_18/src/lib.rs
  compatibility-tests/v1_30/src/lib.rs
  compatibility-tests/v1_34/src/lib.rs
  compatibility-tests/without-backtrace/src/lib.rs
  snafu-derive/src/lib.rs
Labels: maintenance

#121 Add optional conversion to `backtrace::Backtrace`
  Cargo.toml
  src/backtrace_shim.rs
  src/guide/feature_flags.md
Labels: enhancement

#117 Allow default generic parameters on error types
  snafu-derive/src/lib.rs
  tests/generics_with_default.rs
Labels: bug

#109 Improve errors for misused attributes
  compatibility-tests/compile-fail/tests/ui/attribute-duplication.rs
  compatibility-tests/compile-fail/tests/ui/attribute-duplication.stderr
  compatibility-tests/compile-fail/tests/ui/attribute-misuse.rs
  compatibility-tests/compile-fail/tests/ui/attribute-misuse.stderr
  snafu-derive/src/lib.rs
Labels: breaking change, enhancement

#128 Specify minimum versions in Cargo.toml files where possible
  .cirrus.yml
  compatibility-tests/v1_18/Cargo.toml
  compatibility-tests/v1_30/Cargo.toml
Labels: maintenance

#129 Make `source(from)` imply `source(true)`
  compatibility-tests/compile-fail/tests/ui/attribute-duplication.stderr
  snafu-derive/src/lib.rs
  src/guide/attributes.md
  tests/source_attributes.rs
Labels: enhancement
