Repository shepmaster/snafu, pull requests merged in 2019-08, with the labels that each got.

#136 Implement Future for Context instead of TryFuture
  compatibility-tests/futures/src/lib.rs
  src/futures/try_future.rs
  src/futures/try_stream.rs
Labels: enhancement

#143 Do not report errors if we fail to parse a `#[doc]` attribute
  snafu-derive/src/lib.rs
  tests/doc_comment.rs
Labels: bug

#144 Merge 0.4 fixes into master
  CHANGELOG.md
  Cargo.toml
  compatibility-tests/futures/src/lib.rs
  snafu-derive/Cargo.toml
  snafu-derive/src/lib.rs
  src/futures/try_future.rs
  src/futures/try_stream.rs
  tests/doc_comment.rs
Labels: maintenance

#147 Fix parsing of source/backtrace with no parens
  compatibility-tests/compile-fail/tests/ui/attribute-unparseable.rs
  compatibility-tests/compile-fail/tests/ui/attribute-unparseable.stderr
  snafu-derive/src/lib.rs
  tests/multiple_attributes.rs
Labels: bug

#155 Newest rustc-demangle no longer supports Rust 1.18
  compatibility-tests/v1_18/Cargo.toml
Labels: maintenance

#163 async / await is stable in nightly
  compatibility-tests/futures/src/lib.rs
Labels: maintenance
