Repository shepmaster/snafu, pull requests merged in 2019-05, with the labels that each got.

#63 Default display attribute includes the source error description
  snafu-derive/src/lib.rs
  src/guide/the_macro.rs
  tests/default_error_display.rs
Labels: enhancement

#64 Allow identifying special fields with an attribute
  snafu-derive/src/lib.rs
  src/guide/attributes.rs
  tests/backtrace_attributes.rs
  tests/source_attributes.rs
Labels: enhancement

#65 Add a basic comparison to Failure
  src/guide/comparison/failure.rs
  src/guide/comparison/mod.rs
  src/guide/mod.rs
Labels: maintenance

#66 Mention what the crate is about in the README and crate docs.
  README.md
  src/lib.rs
Labels: maintenance

#68 Add license files
  LICENSE-APACHE
  LICENSE-MIT
Labels: maintenance

#71 Add a code of conduct
  CODE_OF_CONDUCT.md
Labels: maintenance

#67 Support recursive error types
  snafu-derive/src/lib.rs
  src/guide/attributes.rs
  src/guide/the_macro.rs
  src/lib.rs
  tests/recursive_error.rs
  tests/source_attributes.rs
Labels: breaking change, bug, enhancement, maintenance

#77 Support Box<dyn Error + Send + Sync> as an error source
  snafu-derive/src/lib.rs
  src/lib.rs
  tests/boxed_error.rs
  tests/boxed_error_trait_object.rs
  tests/send_between_threads.rs
Labels: bug

#79 Migrate to the IntoError trait instead of From + Context
  snafu-derive/src/lib.rs
  src/guide/the_macro.rs
  src/lib.rs
  tests/backtrace.rs
  tests/default_error_display.rs
  tests/mapping_result_without_try_operator.rs
  tests/recursive_error.rs
  tests/send_between_threads.rs
Labels: breaking change, maintenance

#81 Rustfmt the documentation and provide more links
  src/guide/attributes.rs
  src/guide/comparison/failure.rs
  src/guide/generics.rs
  src/guide/the_macro.rs
  src/lib.rs
Labels: maintenance

#80 Derive Debug, Copy and Clone for context selectors
  snafu-derive/src/lib.rs
Labels: breaking change, maintenance

#82 Move backtrace_shim to a new module
  src/backtrace_shim.rs
  src/lib.rs
Labels: maintenance

#83 No longer implement `Borrow`
  snafu-derive/src/lib.rs
Labels: breaking change, maintenance

#86 Add an extension trait for standard library Futures
  .cirrus.yml
  Cargo.toml
  compatibility-tests/futures/.gitignore
  compatibility-tests/futures/Cargo.toml
  compatibility-tests/futures/rust-toolchain
  compatibility-tests/futures/src/lib.rs
  compatibility-tests/futures/tests/futures.rs
  src/futures/mod.rs
  src/futures/try_future.rs
  src/futures/try_stream.rs
  src/guide/feature_flags.rs
  src/lib.rs
Labels: enhancement

#87 Crates.io disallows decimals in feature names
  CHANGELOG.md
  Cargo.toml
  compatibility-tests/futures-0.1/Cargo.toml
  src/futures01/mod.rs
  src/guide/feature_flags.rs
  src/lib.rs
Labels: maintenance
