Repository shepmaster/snafu, pull requests merged in 2020-01, with the labels that each got.

#204 Update failure messages for Rust 1.40
  compatibility-tests/compile-fail/tests/ui/error-reporting.stderr
Labels: maintenance

#203 Make the formatter argument name unlikely to clash with user names
  snafu-derive/src/lib.rs
Labels: bug, found in the field

#205 feat: `allow(single_use_lifetimes)` where applicable
  snafu-derive/src/lib.rs
  tests/single_use_lifetimes_lint.rs
Labels: enhancement
