Repository shepmaster/snafu, pull requests merged in 2021-07, with the labels that each got.

#286 Change the default context selector suffix to Snafu
  README.md
  compatibility-tests/backtrace-shim/tests/backtrace.rs
  compatibility-tests/backtrace-shim/tests/backtrace_delegation.rs
  compatibility-tests/backtraces-impl-backtrace-crate/src/lib.rs
  compatibility-tests/backtraces-impl-std/src/lib.rs
  compatibility-tests/compile-fail/tests/ui/structs/visibility.rs
  compatibility-tests/compile-fail/tests/ui/structs/visibility.stderr
  compatibility-tests/compile-fail/tests/ui/visibility.rs
  compatibility-tests/compile-fail/tests/ui/visibility.stderr
  compatibility-tests/futures/src/lib.rs
  compatibility-tests/v1_34/src/lib.rs
  snafu-derive/src/lib.rs
  snafu-derive/src/parse.rs
  snafu-derive/src/shared.rs
  src/Snafu.md
  src/futures/try_future.rs
  src/futures/try_stream.rs
  src/guide/comparison/failure.md
  src/guide/examples/backtrace.rs
  src/guide/examples/basic.rs
  src/guide/generics.md
  src/guide/opaque.md
  src/guide/structs.md
  src/guide/the_macro.md
  src/lib.rs
  tests/backtrace-optional-enabled.rs
  tests/backtrace-optional.rs
  tests/backtrace.rs
  tests/backtrace_attributes.rs
  tests/basic.rs
  tests/boxed_error_trait_object.rs
  tests/build-leaf-error.rs
  tests/context_selector_name.rs
  tests/default_error_display.rs
  tests/ensure.rs
  tests/generics.rs
  tests/mapping_result_without_try_operator.rs
  tests/multiple_attributes.rs
  tests/name-conflicts.rs
  tests/opaque.rs
  tests/options.rs
  tests/premade_error.rs
  tests/raw_idents.rs
  tests/recursive_error.rs
  tests/send_between_threads.rs
  tests/source_attributes.rs
  tests/stringly_typed.rs
  tests/structs.rs
  tests/structs/backtrace.rs
  tests/structs/backtrace_attributes.rs
  tests/structs/context_selector_name.rs
  tests/structs/display.rs
  tests/structs/from_option.rs
  tests/structs/generics.rs
  tests/structs/source_attributes.rs
  tests/structs/visibility.rs
  tests/structs/with_source.rs
  tests/structs/without_source.rs
  tests/visibility.rs
Labels: breaking change, enhancement, maintenance

#291 Clean up some documentation and prepare for beta release
  CHANGELOG.md
  src/guide/examples/backtrace.rs
  src/guide/examples/basic.rs
  src/guide/troubleshooting/missing_field_source.md
  src/guide/upgrading.md
Labels: maintenance

#293 No need to work around rustfmt issue anymore
  tests/structs.rs
Labels: maintenance

#294 Remove backwards compatibility parsing
  CHANGELOG.md
  compatibility-tests/compile-fail/tests/ui/error-reporting.rs
  compatibility-tests/compile-fail/tests/ui/error-reporting.stderr
  compatibility-tests/compile-fail/tests/ui/visibility.rs
  compatibility-tests/context-selectors-have-documentation/src/lib.rs
  snafu-derive/src/parse.rs
  src/Snafu.md
  src/guide/examples/backtrace.rs
  src/guide/examples/basic.rs
  src/guide/upgrading.md
  tests/backtrace.rs
  tests/basic.rs
  tests/opaque.rs
  tests/options.rs
  tests/visibility.rs
Labels: breaking change, maintenance

#292 Do not enable the guide by default
  Cargo.toml
  src/lib.rs
Labels: breaking change, maintenance

#278 Add ErrorCompat::iter_chain
  src/error_chain.rs
  src/lib.rs
  tests/error_chain.rs
Labels: enhancement
