Repository shepmaster/snafu, pull requests merged in 2025-05, with the labels that each got.

#487 Maintenance
  compatibility-tests/compile-fail/tests/ui/report.stderr
  src/lib.rs
Labels: maintenance

#482 Add #[allow(dead_code)] to the context selector's fail method
  snafu-derive/src/shared.rs
  tests/context-selectors-make-dead-code.rs
Labels: bug, upstream

#488 Split an alloc feature out from the existing std feature
  .cirrus.yml
  Cargo.toml
  compatibility-tests/alloc-only/Cargo.toml
  compatibility-tests/alloc-only/src/main.rs
  src/guide/feature_flags.md
  src/lib.rs
  src/report.rs
Labels: enhancement

#489 Allow naming context selectors
  compatibility-tests/compile-fail/tests/ui/attribute-misuse.rs
  compatibility-tests/compile-fail/tests/ui/attribute-misuse.stderr
  compatibility-tests/compile-fail/tests/ui/context-selector-naming.rs
  compatibility-tests/compile-fail/tests/ui/context-selector-naming.stderr
  snafu-derive/src/lib.rs
  snafu-derive/src/parse.rs
  snafu-derive/src/shared.rs
  src/Snafu.md
  tests/context_selector_name.rs
Labels: enhancement

#497 Update some wording from Discord feedback
  src/guide.md
Labels: found in the field
